export const COLLECTION_NAME_MAX_LENGTH = 1024;
export const COLLECTION_DESCRIPTION_MAX_LENGTH = 16_384;

export type ConflictEntityType =
  'ModelCollection' | 'ModelCollectionMembership' | 'Tag';

export type ConflictReasonCode =
  | 'concurrentUpdate'
  | 'deletedOnServer'
  | 'changedBeforeDelete'
  | 'permissionChanged'
  | 'missingDependency'
  | 'unknown';

export type ConflictResolutionState =
  'ready' | 'resolving' | 'stale' | 'unresolvable';

export interface ModelCollectionConflictValue {
  name: string;
  description: string | null;
  isShared: boolean;
}

export interface MembershipConflictValue {
  collectionName: string;
  modelName: string;
  isMember: boolean;
}

export interface TagConflictValue {
  name: string;
  category: string | null;
  description: string | null;
  color: string | null;
  isAutoGenerated: boolean;
}

interface ConflictViewModelBase {
  conflictId: string;
  conflictVersion: number;
  unresolvedToken: string;
  batchIncarnation: string;
  attemptToken: string;
  entityId: string;
  reasonCode: ConflictReasonCode;
  createdAt: number;
  resolutionState: ConflictResolutionState;
  /**
   * Integrator contract: once a resolve attempt completes (success or
   * failure), the caller MUST change `resolutionState` and/or
   * `resolutionError` from the values in effect when `onResolve` fired for
   * that attempt (e.g. transition through `'resolving'`, or attach a new
   * `resolutionError` string). `ResolutionPanel` latches a synchronous
   * local guard the instant a submission is emitted, to prevent duplicate
   * requests racing ahead of this props round trip; that guard only
   * releases when it observes a change here (or a new `attemptToken`,
   * which remounts the panel). A caller that never changes either field
   * after processing an attempt will leave the button clickable but its
   * submit silently no-op indefinitely for that conflict.
   */
  resolutionError: string | null;
}

export interface ModelCollectionConflictViewModel extends ConflictViewModelBase {
  entityType: 'ModelCollection';
  localValue: ModelCollectionConflictValue | null;
  serverValue: ModelCollectionConflictValue | null;
  submittedValue: ModelCollectionConflictValue | null;
}

export interface MembershipConflictViewModel extends ConflictViewModelBase {
  entityType: 'ModelCollectionMembership';
  localValue: MembershipConflictValue | null;
  serverValue: MembershipConflictValue | null;
  submittedValue: MembershipConflictValue | null;
}

export interface TagConflictViewModel extends ConflictViewModelBase {
  entityType: 'Tag';
  localValue: TagConflictValue | null;
  serverValue: TagConflictValue | null;
  submittedValue: TagConflictValue | null;
}

export type ConflictViewModel =
  | ModelCollectionConflictViewModel
  | MembershipConflictViewModel
  | TagConflictViewModel;

export interface ManualCollectionMergeInput {
  name: string;
  description: string | null;
  isShared: boolean;
}

export type ConflictResolutionActionInput =
  | { kind: 'acceptServer' }
  | { kind: 'keepLocal' }
  | { kind: 'manualMerge'; value: ManualCollectionMergeInput };

export interface ResolveConflictRequest {
  profileId: string;
  conflictId: string;
  conflictVersion: number;
  expectedUnresolvedToken: string;
  batchIncarnation: string;
  expectedAttemptToken: string;
  actionInput: ConflictResolutionActionInput;
}

export interface SelectConflictRequest {
  profileId: string;
  conflictId: string;
}

export interface RefreshConflictsRequest {
  profileId: string;
}

export interface ConflictResolutionCenterProps {
  profileId: string;
  profileName: string;
  conflicts: readonly ConflictViewModel[];
  unresolvedCount: number;
  selectedConflictId: string | null;
  loading: boolean;
  loadError: string | null;
  now?: number;
  returnFocusTo?: HTMLElement | null;
  onSelectConflict: (request: SelectConflictRequest) => void;
  onRefresh: (request: RefreshConflictsRequest) => void;
  onResolve: (request: ResolveConflictRequest) => void;
  onClose: () => void;
}
