//! Independently authored 3MF fixture suite (issue #20).
//!
//! Every fixture is generated by [`catalog`] below and checked into
//! `tests/fixtures/threemf/` together with `manifest.json`, which records each
//! file's SHA-256 and its expected parse outcome. The tests here:
//!
//! * verify the checked-in bytes still match the recorded digest (provenance —
//!   a fixture cannot be silently edited);
//! * verify the reader's observable behaviour against the manifest, for both
//!   the well-formed and the deliberately hostile/corrupt cases.
//!
//! Regenerate after intentionally changing a fixture:
//!
//! ```text
//! cargo test --manifest-path native/Cargo.toml -p model-core \
//!     --test threemf_fixtures -- --ignored regenerate_threemf_fixtures
//! ```

mod threemf_support;

use std::collections::BTreeSet;
use std::fs;
use std::path::PathBuf;

use model_core::threemf;
use model_core::vendor;
use serde::{Deserialize, Serialize};

use threemf_support::{
    box_object, model_document, package, sha256_hex, tiny_png, triangle_object, zip_parts,
    CONTENT_TYPES_PART, CONTENT_TYPES_XML, DEFAULT_MODEL_PART, RELATIONSHIPS_PART, RELS_XML,
};

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct FixtureManifest {
    /// How to reproduce every file listed below.
    generator: String,
    provenance: String,
    fixtures: Vec<FixtureRecord>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct FixtureRecord {
    file: String,
    label: String,
    notes: String,
    sha256: String,
    byte_len: usize,
    #[serde(skip_serializing_if = "Option::is_none")]
    expected: Option<ExpectedScene>,
    #[serde(skip_serializing_if = "Option::is_none")]
    expected_vendor: Option<ExpectedVendor>,
    /// Stable [`threemf::ThreeMfError::code`] for fixtures that must be
    /// rejected. Mutually exclusive with `expected`.
    #[serde(skip_serializing_if = "Option::is_none")]
    expected_error: Option<String>,
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ExpectedScene {
    unit: String,
    vertex_count: usize,
    triangle_count: usize,
    object_count: usize,
    build_item_count: usize,
    part_count: usize,
    part_names: Vec<String>,
    scene_object_count: usize,
    root_object_ids: Vec<String>,
    plate_count: usize,
    bounds_min: [f32; 3],
    bounds_max: [f32; 3],
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ExpectedVendor {
    slicer: String,
    plate_count: usize,
    plate_indices: Vec<u32>,
    filament_types: Vec<String>,
    thumbnail_parts: Vec<String>,
}

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("threemf")
}

fn read_manifest() -> FixtureManifest {
    let path = fixture_dir().join("manifest.json");
    serde_json::from_slice(&fs::read(&path).expect("read 3MF fixture manifest"))
        .expect("parse 3MF fixture manifest")
}

// --- fixture authoring -----------------------------------------------------

/// One authored fixture: the file name, human context, and raw package bytes.
struct Authored {
    file: &'static str,
    label: &'static str,
    notes: &'static str,
    bytes: Vec<u8>,
}

/// Every fixture, authored from first principles rather than captured from a
/// slicer, so the expectations can be derived by hand.
fn catalog() -> Vec<Authored> {
    vec![
        multi_part(),
        transform_chain(),
        color_material(),
        multi_plate(),
        unit_inch(),
        large_grid(),
        malformed_not_a_zip(),
        malformed_missing_model(),
        malformed_triangle_index(),
        malformed_component_cycle(),
        malformed_nan_vertex(),
        malformed_doctype_entity(),
        malformed_external_entity(),
        malformed_deep_nesting(),
        malformed_zip_bomb(),
        malformed_path_traversal(),
    ]
}

fn multi_part() -> Authored {
    let resources = [
        box_object("1", "Bracket", [10.0, 20.0, 5.0], ""),
        box_object("2", "Spacer", [4.0, 4.0, 4.0], ""),
        box_object("3", "Cap", [6.0, 6.0, 2.0], ""),
    ]
    .join("\n");
    let build = r#"    <item objectid="1"/>
    <item objectid="2" transform="1 0 0 0 1 0 0 0 1 20 0 0"/>
    <item objectid="3" transform="1 0 0 0 1 0 0 0 1 0 30 0"/>"#;
    Authored {
        file: "multi_part.3mf",
        label: "multi-part",
        notes: "Three independently named box objects, each placed once by the build.",
        bytes: package(&model_document("millimeter", &resources, build), Vec::new()),
    }
}

fn transform_chain() -> Authored {
    // Object 3 is a component assembly that instances the same box twice under
    // different local transforms; the build item adds a third transform on top,
    // so the fixture pins the whole composition chain.
    let resources = format!(
        "{}\n{}",
        box_object("1", "Unit", [2.0, 2.0, 2.0], ""),
        r#"    <object id="3" name="Assembly" type="model">
      <components>
        <component objectid="1"/>
        <component objectid="1" transform="2 0 0 0 2 0 0 0 2 10 0 0"/>
      </components>
    </object>"#
    );
    let build = r#"    <item objectid="3" transform="0 1 0 -1 0 0 0 0 1 100 50 0"/>"#;
    Authored {
        file: "transform_chain.3mf",
        label: "transform",
        notes:
            "Nested components with scale/translate composed under a rotating build-item transform.",
        bytes: package(&model_document("millimeter", &resources, build), Vec::new()),
    }
}

fn color_material() -> Authored {
    // Material and color resources plus per-object and per-triangle property
    // references. The core reader does not surface appearance yet; this fixture
    // pins that they parse cleanly and never perturb geometry.
    let resources = format!(
        r##"    <basematerials id="10">
      <base name="PLA Red" displaycolor="#FF0000FF"/>
      <base name="PLA Blue" displaycolor="#0000FFFF"/>
    </basematerials>
    <m:colorgroup xmlns:m="http://schemas.microsoft.com/3dmanufacturing/material/2015/02" id="11">
      <m:color color="#12AB34FF"/>
      <m:color color="#FFCC00FF"/>
    </m:colorgroup>
{}
{}"##,
        box_object("1", "Red body", [8.0, 8.0, 8.0], r#" pid="10" pindex="0""#),
        triangle_object_with_properties("2", "Painted fin"),
    );
    let build = r#"    <item objectid="1"/>
    <item objectid="2" transform="1 0 0 0 1 0 0 0 1 0 0 20"/>"#;
    Authored {
        file: "color_material.3mf",
        label: "color + material",
        notes: "basematerials, a material-extension colorgroup, object-level pid/pindex and per-triangle p1/p2/p3.",
        bytes: package(&model_document("millimeter", &resources, build), Vec::new()),
    }
}

fn triangle_object_with_properties(id: &str, name: &str) -> String {
    format!(
        r#"    <object id="{id}" name="{name}" type="model" pid="11" pindex="1">
      <mesh>
        <vertices>
          <vertex x="0" y="0" z="0"/>
          <vertex x="5" y="0" z="0"/>
          <vertex x="0" y="5" z="0"/>
          <vertex x="0" y="0" z="5"/>
        </vertices>
        <triangles>
          <triangle v1="0" v2="1" v3="2" pid="11" p1="0" p2="1" p3="0"/>
          <triangle v1="0" v2="1" v3="3" pid="11" p1="1"/>
          <triangle v1="1" v2="2" v3="3"/>
          <triangle v1="0" v2="3" v3="2"/>
        </triangles>
      </mesh>
    </object>"#
    )
}

fn multi_plate() -> Authored {
    let resources = [
        box_object("1", "Plate one body", [10.0, 10.0, 10.0], ""),
        box_object("2", "Plate two body", [6.0, 6.0, 6.0], ""),
    ]
    .join("\n");
    let build = r#"    <item objectid="1"/>
    <item objectid="2" transform="1 0 0 0 1 0 0 0 1 40 0 0"/>"#;
    let model = model_document("millimeter", &resources, build);
    let slice_info = r#"<?xml version="1.0" encoding="UTF-8"?>
<config>
  <header/>
  <plate>
    <metadata key="index" value="1"/>
    <metadata key="prediction" value="3600"/>
    <metadata key="weight" value="24.5"/>
    <filament id="1" type="PLA" used_g="24.5"/>
  </plate>
  <plate>
    <metadata key="index" value="2"/>
    <metadata key="prediction" value="1800"/>
    <metadata key="weight" value="8.25"/>
    <filament id="1" type="PETG" used_g="8.25"/>
  </plate>
</config>"#;
    let png = tiny_png();
    Authored {
        file: "multi_plate.3mf",
        label: "multi-plate",
        notes: "Bambu/Orca-style slice_info.config describing two plates plus one PNG thumbnail per plate.",
        bytes: package(
            &model,
            vec![
                threemf_support::Part::text("Metadata/slice_info.config", slice_info),
                threemf_support::Part::bytes("Metadata/plate_1.png", png.clone()),
                threemf_support::Part::bytes("Metadata/plate_2.png", png),
            ],
        ),
    }
}

fn unit_inch() -> Authored {
    let resources = box_object("1", "Inch cube", [1.0, 2.0, 0.5], "");
    let build = r#"    <item objectid="1"/>"#;
    Authored {
        file: "unit_inch.3mf",
        label: "unit declaration",
        notes: "Root model declared in inches; the reader reports the declared unit and preserves model-space coordinates (only external model parts are rescaled to the root unit).",
        bytes: package(&model_document("inch", &resources, build), Vec::new()),
    }
}

fn large_grid() -> Authored {
    // 40x40 quads => 1681 vertices / 3200 triangles: large enough to exercise
    // the per-vertex work budget, small enough to stay a tidy repo artifact.
    const N: usize = 40;
    let mut vertices = String::new();
    for row in 0..=N {
        for col in 0..=N {
            vertices.push_str(&format!(
                "          <vertex x=\"{}\" y=\"{}\" z=\"0\"/>\n",
                col as f32, row as f32
            ));
        }
    }
    let mut triangles = String::new();
    for row in 0..N {
        for col in 0..N {
            let a = row * (N + 1) + col;
            let b = a + 1;
            let c = a + N + 1;
            let d = c + 1;
            triangles.push_str(&format!(
                "          <triangle v1=\"{a}\" v2=\"{b}\" v3=\"{d}\"/>\n          <triangle v1=\"{a}\" v2=\"{d}\" v3=\"{c}\"/>\n"
            ));
        }
    }
    let resources = format!(
        r#"    <object id="1" name="Grid" type="model">
      <mesh>
        <vertices>
{vertices}        </vertices>
        <triangles>
{triangles}        </triangles>
      </mesh>
    </object>"#
    );
    let build = r#"    <item objectid="1"/>"#;
    Authored {
        file: "large_grid.3mf",
        label: "large",
        notes: "40x40 triangulated grid (1681 vertices / 3200 triangles).",
        bytes: package(&model_document("millimeter", &resources, build), Vec::new()),
    }
}

fn malformed_not_a_zip() -> Authored {
    Authored {
        file: "malformed_not_a_zip.3mf",
        label: "malformed: not an archive",
        notes: "Plain text with a .3mf extension; must be rejected before any ZIP reader work, not panic.",
        bytes: b"this is not a 3MF package, it is just some bytes\n".to_vec(),
    }
}

fn malformed_missing_model() -> Authored {
    Authored {
        file: "malformed_missing_model.3mf",
        label: "malformed: no model part",
        notes:
            "Valid OPC container whose relationships point at a part that is not in the archive.",
        bytes: zip_parts(&[
            threemf_support::Part::text(CONTENT_TYPES_PART, CONTENT_TYPES_XML),
            threemf_support::Part::text(RELATIONSHIPS_PART, RELS_XML),
            threemf_support::Part::text("Metadata/readme.config", "<config/>"),
        ]),
    }
}

fn malformed_triangle_index() -> Authored {
    let resources = r#"    <object id="1" name="Bad index" type="model">
      <mesh>
        <vertices>
          <vertex x="0" y="0" z="0"/>
          <vertex x="1" y="0" z="0"/>
          <vertex x="0" y="1" z="0"/>
        </vertices>
        <triangles>
          <triangle v1="0" v2="1" v3="9"/>
        </triangles>
      </mesh>
    </object>"#;
    let build = r#"    <item objectid="1"/>"#;
    Authored {
        file: "malformed_triangle_index.3mf",
        label: "malformed: triangle index out of range",
        notes: "A triangle references vertex 9 of a 3-vertex mesh.",
        bytes: package(&model_document("millimeter", resources, build), Vec::new()),
    }
}

fn malformed_component_cycle() -> Authored {
    let resources = r#"    <object id="1" name="A" type="model">
      <components>
        <component objectid="2"/>
      </components>
    </object>
    <object id="2" name="B" type="model">
      <components>
        <component objectid="1"/>
      </components>
    </object>"#;
    let build = r#"    <item objectid="1"/>"#;
    Authored {
        file: "malformed_component_cycle.3mf",
        label: "malformed: component cycle",
        notes: "Two objects reference each other; expansion must terminate instead of recursing forever.",
        bytes: package(&model_document("millimeter", resources, build), Vec::new()),
    }
}

fn malformed_nan_vertex() -> Authored {
    let resources = r#"    <object id="1" name="Poisoned" type="model">
      <mesh>
        <vertices>
          <vertex x="0" y="0" z="0"/>
          <vertex x="NaN" y="0" z="0"/>
          <vertex x="0" y="Infinity" z="0"/>
        </vertices>
        <triangles>
          <triangle v1="0" v2="1" v3="2"/>
        </triangles>
      </mesh>
    </object>"#;
    let build = r#"    <item objectid="1"/>"#;
    Authored {
        file: "malformed_nan_vertex.3mf",
        label: "malformed: non-finite coordinates",
        notes:
            "NaN/Infinity vertex coordinates would poison the bounds and serialize as JSON null.",
        bytes: package(&model_document("millimeter", resources, build), Vec::new()),
    }
}

fn malformed_doctype_entity() -> Authored {
    // Classic "billion laughs": nine levels of entity expansion. The reader
    // must refuse the DOCTYPE outright rather than expanding anything.
    let model = r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model [
  <!ENTITY lol "lol">
  <!ENTITY lol1 "&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;">
  <!ENTITY lol2 "&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;">
  <!ENTITY lol3 "&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;">
  <!ENTITY lol4 "&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;">
  <!ENTITY lol5 "&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;">
  <!ENTITY lol6 "&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;">
  <!ENTITY lol7 "&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;">
  <!ENTITY lol8 "&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;">
  <!ENTITY lol9 "&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;">
]>
<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <metadata name="Title">&lol9;</metadata>
  <resources>
    <object id="1" type="model">
      <mesh>
        <vertices>
          <vertex x="0" y="0" z="0"/>
          <vertex x="1" y="0" z="0"/>
          <vertex x="0" y="1" z="0"/>
        </vertices>
        <triangles><triangle v1="0" v2="1" v3="2"/></triangles>
      </mesh>
    </object>
  </resources>
  <build><item objectid="1"/></build>
</model>"#;
    Authored {
        file: "malformed_doctype_entity.3mf",
        label: "hostile: billion laughs",
        notes: "Recursive internal entity expansion inside a DOCTYPE.",
        bytes: package(model, Vec::new()),
    }
}

fn malformed_external_entity() -> Authored {
    let model = r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model [
  <!ENTITY xxe SYSTEM "file:///etc/passwd">
]>
<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <metadata name="Designer">&xxe;</metadata>
  <resources>
    <object id="1" type="model">
      <mesh>
        <vertices>
          <vertex x="0" y="0" z="0"/>
          <vertex x="1" y="0" z="0"/>
          <vertex x="0" y="1" z="0"/>
        </vertices>
        <triangles><triangle v1="0" v2="1" v3="2"/></triangles>
      </mesh>
    </object>
  </resources>
  <build><item objectid="1"/></build>
</model>"#;
    Authored {
        file: "malformed_external_entity.3mf",
        label: "hostile: XXE",
        notes: "External SYSTEM entity attempting local file disclosure.",
        bytes: package(model, Vec::new()),
    }
}

fn malformed_deep_nesting() -> Authored {
    // Well below any byte ceiling, but far past the nesting limit: a parser
    // that recursed per element would blow its stack here.
    let depth = 5_000;
    let mut model = String::from(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
"#,
    );
    for _ in 0..depth {
        model.push_str("<wrap>");
    }
    model.push_str("<object id=\"1\" type=\"model\"/>");
    for _ in 0..depth {
        model.push_str("</wrap>");
    }
    model.push_str("\n  </resources>\n  <build/>\n</model>");
    Authored {
        file: "malformed_deep_nesting.3mf",
        label: "hostile: XML depth",
        notes: "5,000 levels of nested elements inside <resources>.",
        bytes: package(&model, Vec::new()),
    }
}

fn malformed_zip_bomb() -> Authored {
    // 8 MiB of zeros deflates to a few KB: comfortably over both the ratio
    // limit and the small-entry floor that exempts ordinary tiny XML parts.
    let bomb = vec![0u8; 8 * 1024 * 1024];
    let resources = triangle_object("1", "Decoy");
    let build = r#"    <item objectid="1"/>"#;
    Authored {
        file: "malformed_zip_bomb.3mf",
        label: "hostile: decompression bomb",
        notes: "An 8 MiB all-zero thumbnail part with a ~1000:1 compression ratio.",
        bytes: package(
            &model_document("millimeter", &resources, build),
            vec![threemf_support::Part::bytes("Metadata/plate_1.png", bomb)],
        ),
    }
}

fn malformed_path_traversal() -> Authored {
    let resources = triangle_object("1", "Decoy");
    let build = r#"    <item objectid="1"/>"#;
    let model = model_document("millimeter", &resources, build);
    Authored {
        file: "malformed_path_traversal.3mf",
        label: "hostile: path traversal",
        notes:
            "An archive entry named ../../evil.txt, which must never be treated as a package part.",
        bytes: zip_parts(&[
            threemf_support::Part::text(CONTENT_TYPES_PART, CONTENT_TYPES_XML),
            threemf_support::Part::text(RELATIONSHIPS_PART, RELS_XML),
            threemf_support::Part::text(DEFAULT_MODEL_PART, &model),
            threemf_support::Part::text("../../evil.txt", "owned"),
        ]),
    }
}

// --- tests -----------------------------------------------------------------

#[test]
fn every_authored_fixture_is_checked_in_with_a_matching_digest() {
    let manifest = read_manifest();
    let recorded: BTreeSet<&str> = manifest.fixtures.iter().map(|f| f.file.as_str()).collect();
    let authored: BTreeSet<&str> = catalog().iter().map(|f| f.file).collect();
    assert_eq!(
        recorded, authored,
        "manifest.json and the fixture catalog disagree; regenerate the fixtures"
    );

    for record in &manifest.fixtures {
        let bytes = fs::read(fixture_dir().join(&record.file))
            .unwrap_or_else(|e| panic!("read fixture {}: {e}", record.file));
        assert_eq!(
            bytes.len(),
            record.byte_len,
            "{} changed size on disk",
            record.file
        );
        assert_eq!(
            sha256_hex(&bytes),
            record.sha256,
            "{} does not match its recorded digest",
            record.file
        );
    }
}

#[test]
fn well_formed_fixtures_match_their_expected_scenes() {
    for record in read_manifest().fixtures {
        let Some(expected) = record.expected else {
            continue;
        };
        let bytes = fs::read(fixture_dir().join(&record.file)).expect("read fixture");
        let mesh = threemf::parse_bytes(&bytes)
            .unwrap_or_else(|e| panic!("{} ({}) failed to parse: {e}", record.file, record.label));

        let actual = ExpectedScene {
            unit: mesh.unit.clone(),
            vertex_count: mesh.vertex_count(),
            triangle_count: mesh.triangle_count(),
            object_count: mesh.object_count,
            build_item_count: mesh.build_item_count,
            part_count: mesh.parts.len(),
            part_names: mesh.parts.iter().map(|p| p.name.clone()).collect(),
            scene_object_count: mesh.objects.len(),
            root_object_ids: mesh.root_object_ids.clone(),
            plate_count: mesh.plates.len(),
            bounds_min: mesh.bounds.min,
            bounds_max: mesh.bounds.max,
        };
        assert_eq!(actual, expected, "{} ({})", record.file, record.label);

        assert!(
            mesh.vertices.iter().flatten().all(|c| c.is_finite()),
            "{} produced a non-finite coordinate",
            record.file
        );
        for triangle in &mesh.triangles {
            for index in triangle {
                assert!(
                    (*index as usize) < mesh.vertices.len(),
                    "{} produced an out-of-range triangle index",
                    record.file
                );
            }
        }
    }
}

#[test]
fn rejected_fixtures_fail_with_their_expected_error_code() {
    for record in read_manifest().fixtures {
        let Some(expected_code) = record.expected_error else {
            continue;
        };
        let bytes = fs::read(fixture_dir().join(&record.file)).expect("read fixture");
        match threemf::parse_bytes(&bytes) {
            Ok(_) => panic!(
                "{} ({}) parsed but must be rejected",
                record.file, record.label
            ),
            Err(error) => assert_eq!(
                error.code(),
                expected_code,
                "{} ({}) failed with the wrong code: {error}",
                record.file,
                record.label
            ),
        }
    }
}

#[test]
fn vendor_fixtures_match_their_expected_metadata() {
    for record in read_manifest().fixtures {
        let Some(expected) = record.expected_vendor else {
            continue;
        };
        let bytes = fs::read(fixture_dir().join(&record.file)).expect("read fixture");
        let metadata = vendor::extract_bytes(&bytes)
            .unwrap_or_else(|e| panic!("{} vendor extraction failed: {e}", record.file));

        let actual = ExpectedVendor {
            slicer: format!("{:?}", metadata.slicer),
            plate_count: metadata.plates.len(),
            plate_indices: metadata.plates.iter().filter_map(|p| p.index).collect(),
            filament_types: metadata
                .plates
                .iter()
                .flat_map(|p| p.filament_types.clone())
                .collect(),
            thumbnail_parts: metadata.parts.thumbnails.clone(),
        };
        assert_eq!(actual, expected, "{} ({})", record.file, record.label);

        let thumbnails = vendor::read_plate_thumbnails(&bytes)
            .unwrap_or_else(|e| panic!("{} thumbnail extraction failed: {e}", record.file));
        assert_eq!(
            thumbnails.len(),
            expected.thumbnail_parts.len(),
            "{} thumbnail count",
            record.file
        );
        for thumbnail in thumbnails {
            assert!(
                thumbnail.png_bytes.starts_with(&[0x89, b'P', b'N', b'G']),
                "{} thumbnail {} is not a PNG",
                record.file,
                thumbnail.part_name
            );
        }
    }
}

/// Rewrite every fixture file and refresh `manifest.json`.
///
/// Expected values are recomputed from the reader, so **review the manifest
/// diff**: this is the point at which a behaviour change becomes visible.
#[test]
#[ignore = "regenerates checked-in fixtures; run explicitly"]
fn regenerate_threemf_fixtures() {
    let dir = fixture_dir();
    fs::create_dir_all(&dir).expect("create fixture dir");

    let mut records = Vec::new();
    for authored in catalog() {
        fs::write(dir.join(authored.file), &authored.bytes).expect("write fixture");

        let parsed = threemf::parse_bytes(&authored.bytes);
        let (expected, expected_error) = match &parsed {
            Ok(mesh) => (
                Some(ExpectedScene {
                    unit: mesh.unit.clone(),
                    vertex_count: mesh.vertex_count(),
                    triangle_count: mesh.triangle_count(),
                    object_count: mesh.object_count,
                    build_item_count: mesh.build_item_count,
                    part_count: mesh.parts.len(),
                    part_names: mesh.parts.iter().map(|p| p.name.clone()).collect(),
                    scene_object_count: mesh.objects.len(),
                    root_object_ids: mesh.root_object_ids.clone(),
                    plate_count: mesh.plates.len(),
                    bounds_min: mesh.bounds.min,
                    bounds_max: mesh.bounds.max,
                }),
                None,
            ),
            Err(error) => (None, Some(error.code().to_string())),
        };

        let expected_vendor = if authored.file == "multi_plate.3mf" {
            let metadata = vendor::extract_bytes(&authored.bytes).expect("vendor metadata");
            Some(ExpectedVendor {
                slicer: format!("{:?}", metadata.slicer),
                plate_count: metadata.plates.len(),
                plate_indices: metadata.plates.iter().filter_map(|p| p.index).collect(),
                filament_types: metadata
                    .plates
                    .iter()
                    .flat_map(|p| p.filament_types.clone())
                    .collect(),
                thumbnail_parts: metadata.parts.thumbnails.clone(),
            })
        } else {
            None
        };

        records.push(FixtureRecord {
            file: authored.file.to_string(),
            label: authored.label.to_string(),
            notes: authored.notes.to_string(),
            sha256: sha256_hex(&authored.bytes),
            byte_len: authored.bytes.len(),
            expected,
            expected_vendor,
            expected_error,
        });
    }

    let manifest = FixtureManifest {
        generator: "cargo test --manifest-path native/Cargo.toml -p model-core --test threemf_fixtures -- --ignored regenerate_threemf_fixtures".to_string(),
        provenance: "Authored by hand for PrintFarmer issue #20; no third-party model data. Each package is assembled from raw OPC parts by tests/threemf_fixtures.rs.".to_string(),
        fixtures: records,
    };
    let mut json = serde_json::to_string_pretty(&manifest).expect("serialize manifest");
    json.push('\n');
    fs::write(dir.join("manifest.json"), json).expect("write manifest");
}
