import { useEffect, useRef } from 'react';
import type { UploadJob } from '@shared/ipc';
import { formatBytes } from '../library/model';

export interface UploadQueueDialogProps {
  jobs: UploadJob[];
  busy: boolean;
  error: string | null;
  onPause: (jobId: string) => void;
  onResume: (jobId: string) => void;
  onCancel: (jobId: string) => void;
  onRetry: (jobId: string) => void;
  onConfirmLegacyRetry: (jobId: string) => void;
  onRemove: (jobId: string) => void;
  onReset: () => void;
  onClose: () => void;
}

export function UploadQueueDialog({
  jobs,
  busy,
  error,
  onPause,
  onResume,
  onCancel,
  onRetry,
  onConfirmLegacyRetry,
  onRemove,
  onReset,
  onClose,
}: UploadQueueDialogProps): React.JSX.Element {
  const closeRef = useRef<HTMLButtonElement | null>(null);
  const onCloseRef = useRef(onClose);
  onCloseRef.current = onClose;
  useEffect(() => {
    closeRef.current?.focus();
    const keydown = (event: KeyboardEvent): void => {
      if (event.key === 'Escape') onCloseRef.current();
    };
    document.addEventListener('keydown', keydown);
    return () => document.removeEventListener('keydown', keydown);
  }, []);

  const activeCount = jobs.reduce(
    (count, job) => count + job.summary.queued + job.summary.uploading,
    0,
  );
  return (
    <div className="modal-backdrop">
      <section
        className="upload-queue-dialog"
        role="dialog"
        aria-modal="true"
        aria-labelledby="upload-queue-title"
      >
        <header className="upload-queue-header">
          <div>
            <p className="pane-eyebrow">PrintFarmer transfer center</p>
            <h2 id="upload-queue-title">Upload queue</h2>
            <p>
              {activeCount > 0
                ? `${activeCount} model${activeCount === 1 ? '' : 's'} remaining`
                : 'No active uploads'}
            </p>
          </div>
          <button
            ref={closeRef}
            type="button"
            aria-label="Close upload queue"
            onClick={onClose}
          >
            Close
          </button>
        </header>

        <p className="upload-live-status" role="status" aria-live="polite">
          {busy
            ? 'Updating upload queue.'
            : summarizeJobs(jobs) || 'Upload queue is empty.'}
        </p>
        {error ? (
          <div className="library-alert" role="alert">
            <span>{error}</span>
            <button type="button" disabled={busy} onClick={onReset}>
              Reset queue (keep backup)
            </button>
          </div>
        ) : null}

        <div className="upload-job-list">
          {jobs.length === 0 ? (
            <div className="purposeful-empty-state">
              <h3>Nothing queued</h3>
              <p>
                Select models in the library, then choose Upload to PrintFarmer.
              </p>
            </div>
          ) : (
            jobs.map((job) => {
              const terminal =
                job.summary.queued === 0 && job.summary.uploading === 0;
              const removable = terminal && job.summary.uncertain === 0;
              const retryable = job.items.some(
                (item) =>
                  (item.state === 'failed' ||
                    item.state === 'cancelled' ||
                    item.state === 'uncertain') &&
                  item.error?.retryable === true &&
                  !item.error.duplicateRisk,
              );
              const legacyRisk = job.items.some(
                (item) =>
                  item.state === 'uncertain' &&
                  item.error?.duplicateRisk === true,
              );
              const percent =
                job.totalBytes === 0
                  ? 0
                  : Math.round((job.bytesSent / job.totalBytes) * 100);
              return (
                <article className="upload-job" key={job.id}>
                  <header>
                    <div>
                      <h3>{job.profileName}</h3>
                      <span className={`upload-mode ${job.mode}`}>
                        {job.mode === 'modern'
                          ? 'Idempotent upload'
                          : 'Legacy model-only upload'}
                      </span>
                    </div>
                    <span>{percent}%</span>
                  </header>
                  {job.mode === 'legacyModelOnly' ? (
                    <p className="upload-warning">
                      Legacy server: thumbnails are generated by the server.
                      Interrupted retries may create duplicates.
                    </p>
                  ) : null}
                  <progress
                    value={job.bytesSent}
                    max={Math.max(1, job.totalBytes)}
                    aria-label={`Overall progress for ${job.profileName}`}
                  />
                  <p className="upload-summary">
                    {job.summary.succeeded} succeeded · {job.summary.failed}{' '}
                    failed
                    {' · '}
                    {job.summary.uncertain} uncertain · {job.summary.cancelled}{' '}
                    cancelled
                  </p>
                  <ul className="upload-item-list">
                    {job.items.map((item) => (
                      <li key={item.id}>
                        <div>
                          <strong>{item.displayName}</strong>
                          <span className={`upload-item-state ${item.state}`}>
                            {item.state === 'succeeded' && item.remote === null
                              ? 'already uploaded'
                              : item.state}
                          </span>
                        </div>
                        <progress
                          value={item.bytesSent}
                          max={Math.max(1, item.size)}
                          aria-label={`Upload progress for ${item.displayName}`}
                        />
                        <span>
                          {formatBytes(item.bytesSent)} /{' '}
                          {formatBytes(item.size)}
                        </span>
                        {item.error ? (
                          <p
                            className={
                              item.error.duplicateRisk ? 'upload-warning' : ''
                            }
                          >
                            {item.error.message}
                          </p>
                        ) : null}
                      </li>
                    ))}
                  </ul>
                  <footer>
                    {job.paused ? (
                      <button
                        type="button"
                        disabled={busy}
                        onClick={() => onResume(job.id)}
                      >
                        Resume
                      </button>
                    ) : !terminal ? (
                      <button
                        type="button"
                        disabled={busy}
                        onClick={() => onPause(job.id)}
                      >
                        Pause
                      </button>
                    ) : null}
                    {!terminal ? (
                      <button
                        type="button"
                        disabled={busy}
                        onClick={() => onCancel(job.id)}
                      >
                        Cancel remaining
                      </button>
                    ) : null}
                    {retryable ? (
                      <button
                        type="button"
                        disabled={busy}
                        onClick={() => onRetry(job.id)}
                      >
                        Retry incomplete
                      </button>
                    ) : null}
                    {legacyRisk ? (
                      <button
                        type="button"
                        disabled={busy}
                        onClick={() => onConfirmLegacyRetry(job.id)}
                      >
                        Confirm duplicate risk and upload
                      </button>
                    ) : null}
                    {removable ? (
                      <button
                        type="button"
                        disabled={busy}
                        onClick={() => onRemove(job.id)}
                      >
                        Remove
                      </button>
                    ) : null}
                  </footer>
                </article>
              );
            })
          )}
        </div>
      </section>
    </div>
  );
}

function summarizeJobs(jobs: UploadJob[]): string {
  const summary = jobs.reduce(
    (total, job) => ({
      succeeded: total.succeeded + job.summary.succeeded,
      failed: total.failed + job.summary.failed,
      uncertain: total.uncertain + job.summary.uncertain,
    }),
    { succeeded: 0, failed: 0, uncertain: 0 },
  );
  if (summary.succeeded + summary.failed + summary.uncertain === 0) return '';
  return `${summary.succeeded} uploads succeeded, ${summary.failed} failed, and ${summary.uncertain} have uncertain server status.`;
}
