import type { UploadJob } from '@shared/ipc';
import { formatBytes } from '../library/model';

export interface UploadsWorkspaceProps {
  jobs: UploadJob[];
  busy: boolean;
  error: string | null;
  onPause: (jobId: string) => void;
  onResume: (jobId: string) => void;
  onCancel: (jobId: string) => void;
  onRetry: (jobId: string) => void;
  onConfirmLegacyRetry: (jobId: string) => void;
  onRemove: (jobId: string) => void;
  onReset: () => void;
  onGoToLibrary: () => void;
}

/**
 * Transfers are long-lived, monitorable state that an operator returns to, so
 * this is a place in the rail rather than a modal that has to be dismissed
 * before the rest of the app can be used.
 */
export function UploadsWorkspace({
  jobs,
  busy,
  error,
  onPause,
  onResume,
  onCancel,
  onRetry,
  onConfirmLegacyRetry,
  onRemove,
  onReset,
  onGoToLibrary,
}: UploadsWorkspaceProps): React.JSX.Element {
  const activeCount = jobs.reduce(
    (count, job) => count + job.summary.queued + job.summary.uploading,
    0,
  );

  return (
    <main id="uploads-main" className="uploads-pane" aria-label="Upload queue">
      <header className="service-heading">
        <div>
          <h1 data-uploads-heading tabIndex={-1}>
            Uploads
          </h1>
          <p>
            {activeCount > 0
              ? `${activeCount} model${activeCount === 1 ? '' : 's'} still transferring to PrintFarmer.`
              : 'Transfers to PrintFarmer, with the server outcome recorded for every model.'}
          </p>
        </div>
      </header>

      <p className="upload-live-status" role="status" aria-live="polite">
        {busy
          ? 'Updating upload queue.'
          : summarizeJobs(jobs) || 'Upload queue is empty.'}
      </p>

      {error ? (
        <div className="library-alert" role="alert">
          <span>{error}</span>
          <button type="button" disabled={busy} onClick={onReset}>
            Reset queue (keep backup)
          </button>
        </div>
      ) : null}

      <div className="upload-job-list">
        {jobs.length === 0 ? (
          <div className="purposeful-empty-state">
            <h2>Nothing queued</h2>
            <p>
              Select models in the library, then choose Upload to PrintFarmer.
              Uploads keep running while you work elsewhere in the app.
            </p>
            <button
              type="button"
              className="empty-state-action"
              onClick={onGoToLibrary}
            >
              Go to the library
            </button>
          </div>
        ) : (
          jobs.map((job) => {
            const terminal =
              job.summary.queued === 0 && job.summary.uploading === 0;
            const removable = terminal && job.summary.uncertain === 0;
            const retryable = job.items.some(
              (item) =>
                (item.state === 'failed' ||
                  item.state === 'cancelled' ||
                  item.state === 'uncertain') &&
                item.error?.retryable === true &&
                !item.error.duplicateRisk,
            );
            const legacyRisk = job.items.some(
              (item) =>
                item.state === 'uncertain' &&
                item.error?.duplicateRisk === true,
            );
            const percent =
              job.totalBytes === 0
                ? 0
                : Math.round((job.bytesSent / job.totalBytes) * 100);
            return (
              <article className="upload-job" key={job.id}>
                <header>
                  <div>
                    <h2>{job.profileName}</h2>
                    <span className={`upload-mode ${job.mode}`}>
                      {job.mode === 'modern'
                        ? 'Idempotent upload'
                        : 'Legacy model-only upload'}
                    </span>
                  </div>
                  <span>{percent}%</span>
                </header>
                {job.mode === 'legacyModelOnly' ? (
                  <p className="upload-warning">
                    Legacy server: thumbnails are generated by the server.
                    Interrupted retries may create duplicates.
                  </p>
                ) : null}
                <progress
                  value={job.bytesSent}
                  max={Math.max(1, job.totalBytes)}
                  aria-label={`Overall progress for ${job.profileName}`}
                />
                <p className="upload-summary">
                  {job.summary.succeeded} succeeded · {job.summary.failed}{' '}
                  failed
                  {' · '}
                  {job.summary.uncertain} uncertain · {job.summary.cancelled}{' '}
                  cancelled
                </p>
                <ul className="upload-item-list">
                  {job.items.map((item) => (
                    <li key={item.id}>
                      <div>
                        <strong>{item.displayName}</strong>
                        <span className={`upload-item-state ${item.state}`}>
                          {item.state === 'succeeded' && item.remote === null
                            ? 'already uploaded'
                            : item.state}
                        </span>
                      </div>
                      <progress
                        value={item.bytesSent}
                        max={Math.max(1, item.size)}
                        aria-label={`Upload progress for ${item.displayName}`}
                      />
                      <span>
                        {formatBytes(item.bytesSent)} / {formatBytes(item.size)}
                      </span>
                      {item.error ? (
                        <p
                          className={
                            item.error.duplicateRisk ? 'upload-warning' : ''
                          }
                        >
                          {item.error.message}
                        </p>
                      ) : null}
                    </li>
                  ))}
                </ul>
                <footer>
                  {job.paused ? (
                    <button
                      type="button"
                      disabled={busy}
                      onClick={() => onResume(job.id)}
                    >
                      Resume
                    </button>
                  ) : !terminal ? (
                    <button
                      type="button"
                      disabled={busy}
                      onClick={() => onPause(job.id)}
                    >
                      Pause
                    </button>
                  ) : null}
                  {!terminal ? (
                    <button
                      type="button"
                      disabled={busy}
                      onClick={() => onCancel(job.id)}
                    >
                      Cancel remaining
                    </button>
                  ) : null}
                  {retryable ? (
                    <button
                      type="button"
                      disabled={busy}
                      onClick={() => onRetry(job.id)}
                    >
                      Retry incomplete
                    </button>
                  ) : null}
                  {legacyRisk ? (
                    <button
                      type="button"
                      disabled={busy}
                      onClick={() => onConfirmLegacyRetry(job.id)}
                    >
                      Confirm duplicate risk and upload
                    </button>
                  ) : null}
                  {removable ? (
                    <button
                      type="button"
                      disabled={busy}
                      onClick={() => onRemove(job.id)}
                    >
                      Remove
                    </button>
                  ) : null}
                </footer>
              </article>
            );
          })
        )}
      </div>
    </main>
  );
}

function summarizeJobs(jobs: UploadJob[]): string {
  const summary = jobs.reduce(
    (total, job) => ({
      succeeded: total.succeeded + job.summary.succeeded,
      failed: total.failed + job.summary.failed,
      uncertain: total.uncertain + job.summary.uncertain,
    }),
    { succeeded: 0, failed: 0, uncertain: 0 },
  );
  if (summary.succeeded + summary.failed + summary.uncertain === 0) return '';
  return `${summary.succeeded} uploads succeeded, ${summary.failed} failed, and ${summary.uncertain} have uncertain server status.`;
}
