import { z } from 'zod';

export const SyncEntityType = z.enum([
  'ModelCollection',
  'ModelCollectionMembership',
  'Tag',
]);
export type SyncEntityType = z.infer<typeof SyncEntityType>;

export const SyncOperation = z.enum(['Create', 'Update', 'Delete']);
export type SyncOperation = z.infer<typeof SyncOperation>;

export const SyncVisibility = z.enum(['Private', 'Shared']);
export type SyncVisibility = z.infer<typeof SyncVisibility>;

export const ServerGuid = z.string().uuid();
const EmptyGuid = z.literal('00000000-0000-0000-0000-000000000000');

export const RemoteChange = z
  .object({
    revision: z.number().int().nonnegative(),
    entityType: SyncEntityType,
    entityId: z.union([ServerGuid, EmptyGuid]),
    operation: SyncOperation,
    ownerUserId: ServerGuid.nullish().transform((value) => value ?? null),
    visibility: SyncVisibility,
    actorUserId: ServerGuid,
    timestamp: z.string().datetime(),
  })
  .passthrough();
export type RemoteChange = z.infer<typeof RemoteChange>;

export const ChangesResponse = z
  .object({
    changes: z.array(RemoteChange).max(500),
    nextCursor: z
      .string()
      .max(4096)
      .nullish()
      .transform((value) => value ?? null),
    hasMore: z.boolean(),
    serverRevision: z.number().int().nonnegative(),
  })
  .passthrough();
export type ChangesResponse = z.infer<typeof ChangesResponse>;

export const CollectionSnapshot = z
  .object({
    id: ServerGuid,
    name: z.string().min(1).max(1024),
    description: z
      .string()
      .max(16_384)
      .nullish()
      .transform((value) => value ?? null),
    ownerUserId: ServerGuid.nullish().transform((value) => value ?? null),
    isShared: z.boolean(),
    modelIds: z.array(ServerGuid).max(100_000),
    revision: z.number().int().nonnegative(),
    concurrencyToken: z.string().min(1).max(256),
    createdAt: z.string().datetime().optional(),
    updatedAt: z.string().datetime().optional(),
    memberCount: z.number().int().nonnegative().optional(),
  })
  .passthrough();
export type CollectionSnapshot = z.infer<typeof CollectionSnapshot>;

export const MembershipSnapshot = z
  .object({
    id: ServerGuid,
    collectionId: ServerGuid,
    modelId: ServerGuid,
    revision: z.number().int().nonnegative(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  })
  .passthrough();
export type MembershipSnapshot = z.infer<typeof MembershipSnapshot>;

export const TagSnapshot = z
  .object({
    id: ServerGuid,
    name: z.string().min(1).max(1024),
    category: z
      .string()
      .max(1024)
      .nullish()
      .transform((value) => value ?? null),
    revision: z.number().int().nonnegative(),
    concurrencyToken: z.string().min(1).max(256),
    isAutoGenerated: z.boolean().optional().default(false),
    color: z.string().max(128).nullable().optional().default(null),
    description: z.string().max(16_384).nullable().optional().default(null),
  })
  .passthrough();
export type TagSnapshot = z.infer<typeof TagSnapshot>;

export const CollectionList = z.array(CollectionSnapshot).max(100_000);
export const MembershipList = z.array(MembershipSnapshot).max(100_000);

export const AppliedOperation = z
  .object({
    entityType: SyncEntityType,
    operation: SyncOperation,
    entityId: ServerGuid,
    revision: z.number().int().nonnegative(),
    merged: z.boolean(),
  })
  .passthrough();
export type AppliedOperation = z.infer<typeof AppliedOperation>;

export const ApplySuccess = z
  .object({
    applied: z.array(AppliedOperation).max(500),
    serverRevision: z.number().int().nonnegative(),
  })
  .passthrough();
export type ApplySuccess = z.infer<typeof ApplySuccess>;

export const ApplyConflict = z
  .object({
    entityType: SyncEntityType,
    entityId: ServerGuid,
    reason: z.string().min(1).max(4096),
    server: z.unknown().nullable(),
    submitted: z.unknown().nullable(),
  })
  .passthrough();
export type ApplyConflict = z.infer<typeof ApplyConflict>;

export const ApplyConflictResponse = z
  .object({
    error: z.string().min(1).max(4096),
    conflicts: z.array(ApplyConflict).min(1).max(500),
    serverRevision: z.number().int().nonnegative(),
  })
  .passthrough();
export type ApplyConflictResponse = z.infer<typeof ApplyConflictResponse>;

export interface ApplyOperationRequest {
  entityType: SyncEntityType;
  operation: SyncOperation;
  entityId: string;
  baseRevision: number | null;
  concurrencyToken: string | null;
  collectionId: string | null;
  modelId: string | null;
  name: string | null;
  description: string | null;
  isShared: boolean | null;
}

export interface ApplyRequest {
  operations: ApplyOperationRequest[];
}
